[tox]
envlist = py311-{run,test,lint}

[testenv]
passenv = CI
package=editable
install_command = pip install --extra-index-url=https://arm.sero.gic.ericsson.se/artifactory/api/pypi/proj-gaia-dev-pypi-local/simple/ --trusted-host=arm.sero.gic.ericsson.se {packages}

[testenv:py311-test]
deps =
    pytest
commands =
    test: pytest tests -s {posargs}

[testenv:py311-lint]
deps =
    ruff
    codespell
commands =
    ruff check --exclude=notebooks
    ruff format --check --exclude=notebooks
    codespell --skip="./notebooks,./src/content_generator.egg-info,./out,*.txt,./tests"
