FINAL_EVAL_PROMPT = """
You are tasked with merging different examples of the same document into one cohesive and comprehensive document. 
Each of the example documents has been generated by an LLM and will contain overlapping or redundant information from the others.
The task can be broken into the following steps:
1) Check the requirements of the final document
2) Go through each requirement and for each requirement collect the information from the example documents and rewrite it to fit the final document
3) Do another check on the final document to ensure it strictly meets the requirements
4) return the final document in markdown with no additional comments
Here are the following requirements:

{REQUIREMENTS}
"""
